[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
genesis = "Hshwp4hWwnpygRMjNHu7Mto6PKAuSDQrSALXTA1BBe5T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mrisholukamba/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
